### ISSUE TITLE
won't work on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by decryp2kanon** [fflewddur/tophat#38] opened 2022-10-30 15:20 UTC
already tried `sudo apt install gir1.2-gtop-2.0`

but still no...

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
its a fresh installation of 22.04

![image](https://user-images.githubusercontent.com/60179867/198886482-161e69d1-f3b8-441b-86d7-53932f9f3414.png)

**Comment by fflewddur** [comment] 2022-11-12 18:53
Thanks for reporting this! First, have you restarted since installing the git1.2-gtop-2.0 package? TopHat won't be able to load the GTop binding until after a restart. If it's still not working after that, could you check the shell log for output from TopHat? You can view the log with the command `journalctl -f -o cat /usr/bin/gnome-shell`.

**Comment by vadi2** [comment] 2023-01-08 12:38
Having just installed Ubuntu 22.04.1 LTS, obtaining the `gir1.2-gtop-2.0` package and restarting worked for me.

**Comment by vadi2** [comment] 2023-01-08 12:40
Temperature stats are now available though, and I don't see other packages that I should install. What does the tool use to look at temperatures?

**Comment by fflewddur** [comment] 2023-01-08 20:25
@vadi2 TopHat checks for temperature sensors in /sys/class/hwmon/, but v6 only supported Intel CPUs by accident. I just merged a PR that adds support for AMD processors, so if you're on an AMD system, this is expected behavior until the next release.

**Comment by fflewddur** [comment] 2023-02-11 20:42
@vadi2 Do the temperature stats work as expected with TopHat v7? All AM4 platforms should work at this point, but AM5 depends on new hardware sensors in Linux 6.0+.

**Comment by fflewddur** [comment] 2023-02-11 20:43
@decryp2kanon Were you able to get this working, or are you still getting errors with the latest release of TopHat on Ubuntu 22.04?

**Comment by vadi2** [comment] 2023-02-14 13:19
![image](https://user-images.githubusercontent.com/110988/218750380-27d8025b-e532-4687-bf2f-25c96298d3f8.png)
 I think it works!

**Comment by fflewddur** [comment] 2023-03-19 23:11
Awesome, glad it's working now!

**Closed by fflewddur** 2023-03-19 23:11 UTC
Labels: waiting for info
