### ISSUE TITLE
Preferences page crashes on Ubuntu 24.04

### ISSUE THREAD

**Issue by ashwinikd** [fflewddur/tophat#135] opened 2024-07-13 11:02 UTC
Preference window crashes on clicking preferences icon from both top bar and extension manager list. The error is pasted below:

```
The settings of extension tophat@fflewddur.github.io had an error:

SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:0

Stack trace:
  @file:///home/ashwini/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/prefs.js:24:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

Screenshot of the window:
![image](https://github.com/user-attachments/assets/66628779-fada-4882-8f5e-02d95d1b3e5d)

System information:

- OS: Ubuntu 24.04
- Kernel: Linux 6.8.0-38-generic
- Gnome Shell: 46.0

**Comment by dennisameling** [comment] 2024-07-13 13:13
I ran into the same issue on Ubuntu 24.04. Showing the Technical Details revealed some more details:

```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Clutter/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

So I ran this to install Clutter:

```
sudo apt install gir1.2-clutter-1.0
```

Then did a system restart, and the preferences page now works correctly 🎉

**Comment by ashwinikd** [comment] 2024-07-14 06:32
Thanks. Installing clutter resolves the issue. Is this included somewhere in the docs? This was working correctly on 23.04 and did not work out of the box on 24.04.

**Comment by SylChamber** [comment] 2024-07-22 17:21
Same here, no restart necessary. Ubuntu 24.04.

**Comment by fflewddur** [comment] 2024-10-01 16:37
I've added the gir1.2-clutter-1.0 dependency to the installation docs. I'll close this issue as a duplicate of #137, and will use that issue to track work on removing the need for this dependency.

**Closed by fflewddur** 2024-10-01 16:37 UTC
